# Generated by Django 4.2.1 on 2023-06-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='categories')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='FridgePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='fridges', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото холодильника',
                'verbose_name_plural': 'Фото холодильников',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное название товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('avaliable', models.BooleanField(default=True, verbose_name='В продаже')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна-производитель',
                'verbose_name_plural': 'Страны-производители',
            },
        ),
        migrations.CreateModel(
            name='OvenPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='ovens', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото духовки',
                'verbose_name_plural': 'Фото духовок',
            },
        ),
        migrations.CreateModel(
            name='TVOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Операционная система')),
            ],
            options={
                'verbose_name': 'Операционная система ТВ',
                'verbose_name_plural': 'Операционные системы ТВ',
            },
        ),
        migrations.CreateModel(
            name='TVOuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название (HDMI/AV/...)')),
            ],
            options={
                'verbose_name': 'Выход',
                'verbose_name_plural': 'Выходы',
            },
        ),
        migrations.CreateModel(
            name='TVPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='tvs', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото ТВ',
                'verbose_name_plural': 'Фото ТВ',
            },
        ),
        migrations.CreateModel(
            name='TVresolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Разрешение экрана ТВ',
                'verbose_name_plural': 'Разрешения экранов ТВ',
            },
        ),
        migrations.CreateModel(
            name='WMPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='wms', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото стиральной машины',
                'verbose_name_plural': 'Фото стиральных машин',
            },
        ),
        migrations.CreateModel(
            name='WM',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('mods', models.PositiveIntegerField(verbose_name='Количество режимов')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность Вт')),
                ('kg', models.PositiveIntegerField(verbose_name='Максимальная загрузка Кг')),
                ('dry', models.BooleanField(default=True, verbose_name='Отжим')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.wmphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Стиральная машина',
                'verbose_name_plural': 'Стиральные машины',
            },
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('diag', models.PositiveIntegerField(verbose_name='Диагональ экрана в дюймах')),
                ('outputs', models.CharField(max_length=255, verbose_name='Выходы')),
                ('smart', models.BooleanField(default=True, verbose_name='Смарт-ТВ')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.tvphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.tvos', verbose_name='Операционная система')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.tvresolution', verbose_name='Разрешение матрицы')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
            },
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('effectivity', models.PositiveIntegerField(verbose_name='Ээнергоэффективность Вт')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность Вт')),
                ('liters', models.PositiveIntegerField(verbose_name='Объём в литрах')),
                ('freeze', models.BooleanField(default=True, verbose_name='Режим разморозки')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.ovenphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Духовка',
                'verbose_name_plural': 'Духовкки',
            },
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('containers', models.PositiveIntegerField(verbose_name='Количество отсеков')),
                ('power', models.CharField(max_length=255, verbose_name='Энергоэффективность Вт')),
                ('liters', models.PositiveIntegerField(verbose_name='Объём в литрах')),
                ('freeze', models.BooleanField(default=True, verbose_name='Режим заморозки')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.wmphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Холодильник',
                'verbose_name_plural': 'Холодильники',
            },
            bases=('catalog.item',),
        ),
    ]
