# Generated by Django 4.2.1 on 2023-06-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='cooker', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото мультиварки',
                'verbose_name_plural': 'Фото мультиварок',
            },
        ),
        migrations.CreateModel(
            name='DishWasherPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='dishwashers', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото посудомоечной машины',
                'verbose_name_plural': 'Фото посудомоечных машин',
            },
        ),
        migrations.CreateModel(
            name='DryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='dry', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото сушилки',
                'verbose_name_plural': 'Фото сушилок',
            },
        ),
        migrations.CreateModel(
            name='MicrowavePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='microwave', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото сушилки',
                'verbose_name_plural': 'Фото сушилок',
            },
        ),
        migrations.CreateModel(
            name='VacumCleanerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фотографии')),
                ('img', models.ImageField(upload_to='vacum', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото пылесоса',
                'verbose_name_plural': 'Фото пылесосов',
            },
        ),
        migrations.AlterField(
            model_name='oven',
            name='effectivity',
            field=models.PositiveIntegerField(verbose_name='Энергоэффективность Вт'),
        ),
        migrations.CreateModel(
            name='Vacum',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('effectivity', models.PositiveIntegerField(verbose_name='Энергоэффективность Вт')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность Вт')),
                ('mods', models.PositiveIntegerField(verbose_name='Количество режимов работы')),
                ('cord_len', models.PositiveIntegerField(verbose_name='Длина шнура')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.vacumcleanerphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Пылесос',
                'verbose_name_plural': 'Пылесосы',
            },
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='Microwave',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('into', models.BooleanField(default=True, verbose_name='Встраивается')),
                ('effectivity', models.PositiveIntegerField(verbose_name='Энергоэффективность Вт')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность Вт')),
                ('mods', models.PositiveIntegerField(verbose_name='Количество режимов работы')),
                ('defrost', models.BooleanField(default=True, verbose_name='Режим разморозки')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.microwavephoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Микроволновка',
                'verbose_name_plural': 'Микроволновки',
            },
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='DryMashine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('into', models.BooleanField(default=True, verbose_name='Встраивается')),
                ('effectivity', models.PositiveIntegerField(verbose_name='Энергоэффективность Вт')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность Вт')),
                ('mods', models.PositiveIntegerField(verbose_name='Количество режимов работы')),
                ('cord_len', models.PositiveIntegerField(verbose_name='Длина шнура')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.dryphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Сушильная машина',
                'verbose_name_plural': 'Сушильные машины',
            },
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='DishWasher',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('into', models.BooleanField(default=True, verbose_name='Встраивается')),
                ('effectivity', models.PositiveIntegerField(verbose_name='Энергоэффективность Вт')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность Вт')),
                ('liters', models.PositiveIntegerField(verbose_name='Объём в литрах')),
                ('spend', models.PositiveIntegerField(verbose_name='Расход воды в литрах')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.dishwasherphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Посудомоечная машина',
                'verbose_name_plural': 'Посудомоечные машины',
            },
            bases=('catalog.item',),
        ),
        migrations.CreateModel(
            name='Cooker',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.item')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('into', models.BooleanField(default=True, verbose_name='Встраивается')),
                ('effectivity', models.PositiveIntegerField(verbose_name='Энергоэффективность Вт')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность Вт')),
                ('mods', models.PositiveIntegerField(verbose_name='Количество режимов работы')),
                ('defrost', models.BooleanField(default=True, verbose_name='Режим разморозки')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.country', verbose_name='Страна-производитель')),
                ('image', models.ManyToManyField(to='catalog.cookerphoto', verbose_name='Фото')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'мультиварка',
                'verbose_name_plural': 'мультиварка',
            },
            bases=('catalog.item',),
        ),
    ]
